// <auto-generated />
namespace EngeesCollege.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ApplyAnnotationToInstructorAge : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ApplyAnnotationToInstructorAge));
        
        string IMigrationMetadata.Id
        {
            get { return "202004240733019_ApplyAnnotationToInstructorAge"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
